---
title: "Venezuela election; Supreme court reform bill; McDonald's predicament"
author: Ben
date: 07-29-2024
categories:
  - election
  - Venezuela
  - market
  - US
---


# Venezuela's election very much rigged
["Nations Denounce Venezuelan Election, Demanding Transparency"](https://www.nytimes.com/2024/07/29/world/americas/countries-concern-venezuela-election-results.html)

- Maduro declared himself a winner in the presidential election, reportedly earning 51.2% of the votes when 80% of the votes werw counted. Protests are breaking out and "pro-government paramilitaries responded by opening fire in the air and police shot tear gas to disperse the protests."

  - "The electoral authority has yet to publish any results on its website, breaking with tradition. Moreover, opposition poll witnesses at many voting stations were prevented by electoral officials and soldiers from receiving a paper tally of results, in breach of the regulations and precedent."

  - "Mr. Maduro appeared to dig in, with his government announcing that it was investigating top opposition leaders, accusing them of hacking the electoral computer systems."

  - "The move by the electoral authority to not release detailed voting results, which it had routinely done in past elections."

- Also this [FT article](https://www.ft.com/content/dd6f8130-7400-4078-964d-23d9abf12dc6)

- Any sactions? "US negotiations with [Maduro] government and easing of sanctions on Venezuela’s vital oil industry had helped pave the way for Sunday’s voting. For now, the administration said it was not considering retroactively altering previously issued oil licenses."

- regional pressure: "On Monday night, Brazil, Colombia and Mexico were negotiating a joint statement to call on Venezuela to release voting records from each polling station."

- But "Cuba, Serbia, Nicaragua, Russia, Bolivia and Honduras" along with Iran and China congratulated Maduro.



# Biden's Supreme Court reform bills (proposed)
["Warning of ‘Extreme’ Agenda, Biden Calls for Supreme Court Overhaul"](https://www.nytimes.com/2024/07/29/us/politics/biden-supreme-court-austin-texas.html)


- Term limits and "enforceable code of ethics on the justices" are the core elements.

- The move is interpreted as "an election-year intention to try to stop what many in his party feel is the Supreme Court’s ideological drift into conservatism."

- Background

  - "Earlier this month, the court issued a 6-to-3 ruling that grants broad immunity to presidents from prosecution for actions they take while in office. Mr. Biden called for a constitutional amendment that would limit such immunity."
  
  - "Over the past two years, Justice Clarence Thomas has become embroiled in ethical scandals for failing to disclose gifts and luxury trips bestowed by a billionaire benefactor. Justice Samuel A. Alito Jr. has faced scrutiny about why flags associated with the Jan. 6, 2021, attack on the Capitol flew outside his homes."


# McDonald's predicament

- "McDonald’s has suffered its first global drop in sales since 2020." "1 per cent year on year in the three months to the end of June" both internationally and domestically (though more decline international). Net profit also declined by 12%.

- Possibly the post-pandemic consumer strength has finally peaked? If so, the decline would be due to weak demand or purchasing power.

- The prices climbed up: " the average cost of a Big Mac Meal had risen 27 per cent since 2019, to $9.29 in the US."

- Morgan Stanley says the company's "reputation for value" has diminished recently.

