---
title: "VP pick"
date: 07-26-2024
author: Ben
categories: 
  - election
---

# Mark Kelly as VP?
["Spaceman, Senator, V.P. Pick? Kamala Harris Sizes Up Mark Kelly."](https://www.nytimes.com/2024/07/26/us/politics/mark-kelly-kamala-harris-vp.html)

- AZ Sen. Mark Kelly has an impressive resume: "He is the working-class son of New Jersey police officers, a Navy pilot who flew 39 combat missions off the U.S.S. Midway in Operation Desert Storm, and a NASA astronaut and engineer who collected debris from the Columbia disaster, commanded a shuttle as the United States returned to space and flew the Space Shuttle Endeavour’s final mission" and "is married to Gabrielle Giffords." He bonded with McCain, an important figure to remember in AZ and gained respect from AZ Republicans.

- But the real strength is on the border issue. "Mr. Kelly’s approach to the border embraces barriers like Mr. Trump’s wall in some places, though not across the entire frontier. He has also called for an immigration policy that treats migrants with respect and maintains asylum options."

