---
title: Overheating?
author: 
  - name: Ben
    email: bson3@gmu.edu
date: 10-15-2024
categories:
  - central bank
  - Brazil
---

# A parallel between BCB and Fed?
[Giles' Central Banks News Letter](https://ep.ft.com/permalink/emails/eyJlbWFpbCI6ImNkNDIwZDhjMzFjZTRiZmFhYzNiZjE3Mjg2IiwgInRyYW5zYWN0aW9uSWQiOiIyYzZhYTBmNy0wMmVhLTQ0MGUtODA1Yy1iMzBhMGRlMmIxMDkiLCAiYmF0Y2hJZCI6IjNmOWJhOTk5LTU4NjUtNDQ2Yi05YWUyLWQ1ZmM3MzEyMDRiZCJ9)


- Maybe there's a hard-to-miss parallel between the Brazilian and the US economies, in terms of their cycles. Brazilian one seems to be about a year in advance.

  - BCB, the Brazilian central bank, is seeing the economy overheating and started raising rates.
  - While Lula was opposed to the previous governor, Neto, preferences for higher rates, he's silent with the current one, Galipolo, who switched the position to align with Neto's hawkish stances. *So maybe, as far as their people are put in place, populist leaders are okay with the actual policies not coming their way?*
  
- The US market, of course, is different than Brazil's, in that the records read much more optimisically. 
  
  - But it is also true that excess demands are emerging. Fed, for now, seems to see this more of a blip than something systematic.
  
