---
title: Walz and China; Unkraine in Russia; Sado Mines"
author: Ben
date: 08-11-2024
categories:
  - election
  - Korea
  - China
---

# Japanese and South Korean governments are covering up a dark truth about Sado Mine.
["Japan’s Sado Island Gold Mines Designated as UNESCO World Heritage Site With South Korea’s Backing"](https://thediplomat.com/2024/08/japans-sado-island-gold-mines-designated-as-unesco-world-heritage-site-with-south-koreas-backing/)

- "Sado Island Gold Mines’ designation as a UNESCO World Heritage Site in late July."


- Why the UNESCO recognition?: "[S]ome 50 mines whose long history traverses Japan’s traditional era, industrialization, and imperialism."
  - "Japan’s successful UNESCO application for the Sado mines is based solely on their legacy from the Edo period (1603-1867)."
  - By 17th century, the mines achieved an unparalleled manual gold purification system, along with much cultural richness around it.
  - Tokyo's argument: the mines are indicative of "the socio-technical sophistication of the Edo period, which played an invaluable role in both Japan’s socio-cultural development and global trade."
  
- The problem: while the application to UNESCO was built around the pre-modern period, the history of the Sado mines didn't stop there. 

  - the late 19th through early 20th centuries: Sado mines funded the militarist government.
  - Japan started fixing the yen to gold after the Sino-Japan War. Mitsubishi Materials took over the mines' operations. The gold mined out of Sado mines bought warships and weapons. Through the annexation of Korea, Russo-Japanese War, and the second Sino-Japanese war the Mitsubishi-owned mines "bankrolled" Japanese war efforts. 
  - **Forced labor**: 
    - In the Pacific War, the mines turned themselves into other war-related minerals such as copper and zinc. But Mitsubishi struggled the government's production target.
    - "Japan’s National General Labor Mobilization Law, passed in 1938, enabled Mitsubishi to collect forced laborers from Korea in early 1939." About 2300 were estimated to be forced to work in the mines. The victims had to pay their own mining tools while their pays slashed. Their families were brought in to prevent their escapes. They were put into the most grueling and dangerous tasks.

- Cover-up efforts: The Japanese authorities minimized, downplayed, and distorted the labor abuse in the war efforts of the Sado mines during WWII even though UNESCO inquired if they would cover the 'whole' story.

  - The practice is not an isolated incident. A series of historical revisionism and denialism while trying to glorify Japanese historical 'heritage' have taken place recently. This tendency is deeply entrenched in the long-held Japanese foreign policy philosophy.
  
  - **"The Kishida administration has found a perfect accomplice in South Korea’s President Yoon Suk-yeol in laundering Japan’s history."** "The Yoon administration has plumped for South Korea’s New Right movement, which justifies Japan’s occupation of Korea as a source of modernity and enlightenment and glosses over colonial atrocities and the elite’s collaboration."

# Ukraines Incursion into Russia
["Russian reinforcements fail to push back Ukrainian incursion"](https://www.ft.com/content/7dcb3009-ec9a-417a-b2e1-01c26c9349a0)

- "Russia has failed to push back Ukrainian troops in the Kursk region despite sending in reinforcements as the incursion enters its sixth day."

  - "[V]erified videos and photographs show Ukrainian troops and equipment have advanced 30km inside Russia since the operation began on Tuesday, moving further into Kursk and occupying the town of Sudzha near the Russian border," which the Russian authorities are trying to downplay.
  
- "Russia has evacuated more than 76,000 civilians from the Kursk border region. Smirnov referred to the Ukrainian forces as sabotage and reconnaissance groups, and said they had caused panic."

- political intentions?: "Analysts have said Ukraine may be seeking to use the Kursk offensive to improve its position in potential talks. It is losing territory and men in eastern Ukraine and is still struggling to resolve ammunition and manpower shortages."

# Walz is no 'pro-China' guy.
["Tim Walz’s Long Relationship With China Defies Easy Stereotypes"](https://www.nytimes.com/2024/08/11/us/tim-walz-china.html)

- He taught in China and visited the country 30 times, but is skeptical of the country's human rights situations.

  - He taught at a high school in southern China, for one year, immediately after the Tinanmen Square Massacre.
  - As high school teachers, Walz and his wife visited China many times, often bringing students along to introduce them to a different culture.
  
- While in Congress, "[h]e took a special interest in Tibet and Hong Kong, meeting with both the Dalai Lama and Joshua Wong, a prominent Hong Kong pro-democracy activist."

  