---
title: "Iran's new president; US political media mystery"
categories:
  - Iran
  - US
  - election
  - finance
  - admin
date: 07-16-2024
author: Ben
---

# Iran's new president

["Iran’s New President Promises Changes. Can He Deliver?"](https://www.nytimes.com/2024/07/16/world/middleeast/iran-new-president-pezeshkian.html)

- "Masoud Pezeshkian, a widowed doctor, portrays himself as a reformer who can bring social and economic shifts." "He has portrayed himself as a modern leader for a new era in Iran, a religious man who considered his wife an equal partner when she was alive." 

  - He "has sought to come across not as a disrupter but as a more pragmatic fixer." To be a fixer though, he "will have to bargain with Mr. Khamenei."
  
  - He is "Iran's most credentialed president" with the academic background and foreign-language fluency--and training in Harvard. He was also a student activist during the revolution and a volunteer surgeon during the Iran-Iraq war.

- In a column, he described his foreign policy as 'opportunity-driven.' The ties with China and Russia are emphasized; the cooperation with Europe is open; but wouldn't back down to the US pressure. (*in an optimistic interpretation, the last one would be more of face-saving?*)

- Critics say his reform agendas are limited against the deeply entrenched Iranian establishment. 

# BOA problems
["Bank of America profits fall as it pushes up provision for bad loans
"](https://www.ft.com/content/de3e99c4-9b1f-4850-aa54-489cb684ac7f)

- "BofA’s profits fell 7 per cent to $6.9bn, [though] a smaller drop than the 10 per cent analysts had projected." Their "interest income fell for the third quarter in a row" despite the growth in other areas of Wall Street activities.

- In essence, an indicator showing "strain of higher rates on banks and borrowers"

# Not news: bothsidesism mystery

*It is really a great mystery (and thus pure pain to me who's too partisan and emotionally invested to remain a simple bystander) as to how bothsidesism is prevalent in the election year mainstream news media in the United States and beyond. I can only conjecture that the real culprit is the desk given that the contents aren't as extremely normalizing the far-right as the titles and images. Nonetheless, the extent to which the media avoid confronting the apparent anti-democratic and rule-breaking aspect of the American far right is mind-boggling.*

