project:
  type: website

website:
  title: "Myopia Blog"
  navbar:
    right:
      - text: "{{< iconify ic:outline-house height=25px >}}"
        href: https://textvulture.github.io
      - text: "{{< iconify logos:twitter height=19px >}}"
        href: https://twitter.com/Byunghwan_Son
      - text: "{{< iconify simple-icon:bluesky height=19px >}}"
        href: https://bsky.app/profile/textvulture.bsky.social       
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

#title-block-banner: #FFDDFF
