project:
  type: website

website:
  title: "Myopia Blog"
  navbar:
    right:
      - text: "{{< iconify simple-line-icons:home height=27px >}}"
        href: https://textvulture.github.io
      - text: "{{< iconify logos:bluesky height=24px >}}"
        href: https://bsky.app/profile/textvulture.bsky.social        
      - text: "{{< iconify logos:twitter height=22px >}}"
        href: https://twitter.com/Byunghwan_Son
     
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

#title-block-banner: #FFDDFF
