---
title: "Harris surge; Tough Job market; Chinese pressure on Taiwan"
author: Ben
categories: 
  - US
  - election
  - China
  - Taiwan
date: 07-22-2024
---

# Harris rising fast, out-raising funds against Trump

["Harris Seizes Control, Clearing Field, Raising Cash and Slamming Trump"](https://www.nytimes.com/2024/07/22/us/politics/kamala-harris-trump-2024-election.html)

- Just in 24 hours after Biden announced that he steps aside endorsing Kamala Harris, vice president is rapidly clearing the path towards the party's nominee.

  - Campaign Donations: "The Harris campaign announced on Monday that it had raised $81 million in her first 24 hours, a record sum, from 888,000 unique contributors."; "The leading pro-Biden super PAC, Future Forward, which has become a pro-Harris operation, said that it had unlocked $150 million in the last day with $60 million in new pledges, plus $90 million that had previously been frozen while Mr. Biden’s fate hung in the balance."
  
- The next step on the process: "on Wednesday, when the rules committee of the Democratic National Convention is scheduled to meet to set a date for a virtual roll-call vote of the state delegations." 

- "A survey by The Associated Press showed she had more than half the support she needed, with the backing of 1,350 of the 1,976 delegates she needs."; Top Dems, excluding Schummer and Jefferies, promptly endorsed Harris.

  - *While the media try to read too much into the lack of outright endorsement from Schummer-Jefferies, it is only natural that the official head of the party at the two chambers try to appear neutral. It might counter, though perhaps only marginally, the narrative that Harris clinching the nomination without an open primary is undemocratic. The prudence might also counter the long-standing conspiracy theory of the far right.*
  
# Tough US Job Market

["US graduates face cut-throat job market as companies scrap internships"](https://www.ft.com/content/b3684ec2-53ba-4fc3-9f21-c7454c310d3b)

- major companies in US are cutting internships: "Goldman Sachs hired 200 fewer summer analysts this year than in 2023. JPMorgan reduced the size of its own class of summer analysts by 600, more than ten per cent of the total. Tesla rescinded its internship offers just weeks before students were due to start."

- ZipRecruiter says that the year-to-year difference is negative 14 percent. The "traditional, white-colllar" jobs are particularly getting cut.

- Much less enthusiasm: "Sean McGowan, director of employer relations at Carnegie Mellon University, said companies had this year taken months longer than normal to commit to attending his college’s hiring fairs for summer internships. Those that did come relied more heavily on virtual interviews, instead of flying out recruiters to meet students."

- The trend made the competition more intense: "Goldman Sachs received 315,000 applications for fewer than 3,000 roles. JPMorgan received 493,000 applications, an 82 per cent increase from last summer."


# China ramping up the pressure on the new Taiwanese president

["Taiwan’s Blunt-Talking Leader Faces China’s Backlash"](https://www.nytimes.com/2024/07/16/world/asia/taiwan-china-lai-ching-te.html)

- Lai Ching-te's campaign promise was to maintain Tsai Ing-wen's China policy which was to avoid confrontations. The policy itself might not have changed, but his speeches on China became much "blunter."

- The "officials in Beijing seemed taken aback by how starkly he drew a line between Taiwan and China in his high-profile May inauguration speech," in which he stated that "dialogue with Beijing is only possible if the two sides negotiate as separate equals, not ... based on the idea that each side accepts that it is part of one Chinese nation."

  - Taiwanese leaders emphasizing equality is not new; but doing so in the inauguration speech, given its symbolic importance, is new.
  
- Beijing has attempted some military forays into Taiwan's aerial and maritime territories but is worried that such pressures are not resulting in the desired effect.

  - Beijing released a new 'guideline' furthering and detailing the 'illegality' of independence movement. Taiwanese authority warned their citizens about traveling to China. Mr. Lai, in response, wrote in the social media that "Democracy is not a crime; autocracy is what’s truly malicious."

  