---
title: "Spy disaster in Korea; Post-Brexit conditions; Israel Spies"
categories:
  - intelligence
  - Korea
  - Israel
  - Brexit
date: 08-01-2024
author: Ben
---

# Failture of Counter-intelligence in Korea
["정보사 블랙요원 정보 유출, 건국 이래 최대 방첩 실패"](https://www.hani.co.kr/arti/politics/politics_general/1151722.html)

- It was revealed earlier in the week that the list of 'black-op' agents of South Korea was leaked by a military (the Intelligence Command) employee (a former military NCO). 

- Many of the agents were ordered back, but Rep Yoon worries that much of the intelligence resources/assets as well as the agents' family members might still be left out.

- Hand Dong-hoon, the leader of presidential party, PPP, blames the Democratic party for this accident, assertiong that has been sitting on the Anti-espionage act bill. Rep Yoon, however, counters that the Democratic party in fact has been demanding for the revision consistently. The focus of the debate was the legal matters about the National Security Law.

- The incidence is hardly a new one. According to [this article](https://m.khan.co.kr/politics/defense-diplomacy/article/202407281138001), it was revealed in 2018 that a team leader in the Intelligence Command had sold secret to China and Japan, $1000 per item, since 2013. In 2017, about 150 million pages of secret was hacked out of the Integrated Defense Data Center.   

# EU not happy with Britain failing to honor the Brexit divorce deal

["EU issues UK with list of demands if it wants better relationship"](https://www.ft.com/content/43593399-6e31-4b9f-81ec-a06851938706)

- "Brussels has warned the UK it must fully implement existing Brexit agreements on Northern Ireland and the rights of EU citizens living in Britain" at the time when the new PM wants to improve Britain's relationship with the EU.

# Israel's intelligence efforts?

["Israel’s spies take their revenge"](https://www.ft.com/content/f2d43ee7-1584-4a0a-8148-99d395ae8ad2)

- "After the humiliation of October 7, intelligence services are hitting back where their enemies feel safest" -- Tehran and Beirut. The Israli intelligence officers view these twin assassinations as a "redemption of sorts."

- But "over the decades assassinations have proven to be only a short-term fix, at best, and often a strategic liability."

