---
title: "Venezuela; "
categories:
  - Venezuela
  - election
  - finance
author: Ben
date: 07-10-2024
---

# Voting Suppression Abroad, Venezuela

["They Fled Oppression at Home, but It Followed Them Abroad"](https://www.nytimes.com/2024/07/10/world/americas/venezuela-election-voters-abroad.html)

-   Preseidential election is coming up in Venezuela. Venezuelans living outside the country need to register to be able to vote. But the authorities are effectively blocking the regristration using the law that "citizens abroad to possess “residence” or “legal permanence” in the country where they live to be eligible to vote."

    -   Of 21 mn electorate, between 3.5 and 5.5 mn live abroad. Many of these people probably would vote against Maduro, who is not currently doing very well in the polls

-   Essentially a case of disenfranchisement.

# UBS vs. Switzerland

["How UBS fell out with Switzerland’s establishment after rescuing Credit Suisse"](https://on.ft.com/4bAyh0D)

-   UBS, a Swiss-based investment bank and financial service company, seems to have a bad relationship with the Swiss authority.

    -   UBS bought (or 'saved') Credit Suisse last year. The deal was controversial as it generated about \$ 17bn loss around the world. Local politicians weren't happy with it either ("UBS was handed the “deal of the century” at the expense of the Swiss people").

-   The subjects over which the two party publicly quarrel are various: e.g., executive pay; capital requirements. The latter created frictions as some believe that the failures of the Credit Suisse weren't due to the lack fo capital.

    -   But "\[m\]uch of the recent disagreement centres around plans to bolster the country’s financial system after the body blow of losing its second-biggest bank, in a public spat playing out between a group of newly hired leaders."

# UK foreign policy under a Labour government

("What does Labour’s win mean for British foreign policy?")\[https://www-economist-com.mutex.gmu.edu/britain/2024/07/09/what-does-labours-win-mean-for-british-foreign-policy\]

-   the expectation is that Sr. Keir Starmer wants to portray the UK differently than before: "Almost overnight an exaggerated image of Britain as a chaotic clown-show—true under Boris Johnson, a bit less so for Rishi Sunak—has flipped to an idealised image of stable government led by a serious-minded centrist."

    -   Much of the foreign policy fundamentals though will remain unchanged. Unlike, Corbyn, for example, the commitment to NATO is strong.

    -   "As for China, Labour has promised a full audit of its relationship with the country" and some incoming cabinet members made some hawkish remarks. But, in reality, things will remain pretty much the same, which is "to maintain openness towards consumer-goods trade" while "taking a sceptical view of Chinese investment in nuclear, telecoms and other sensitive areas."

-   The discontinuity will be on the relationship with the EU, which is expected to improve (though the party has ruled out rejoining the EU).

    -   A security-and-defence cooperation agreement is a possibility.
