---
title: "GLOA 720 Syllabus (<red>practice</red>)"
subtitle: Spring 2025
format: 
  html:
    other-links: 
      - text: Personal Webpage
        icon: house
        href: https://textvulture.github.io/
      - text: GLOA Profile
        href: https://globalaffairs.gmu.edu/
        icon: buildings
      - text: GitHub
        href: https://github.com/textvulture
        icon: github
editor: visual
author: 
  - name: "Byunghwan 'Ben' Son (bson3@gmu.edu)"
    affiliations:
      - name: Global Affairs, George Mason Uiversity
        url: https://globalaffairs.gmu.edu/
bibliography: references.bib
csl: C:\\Users\\kalka\\Dropbox\\latex\\apsa.csl
toc: true
toccolor: blue
smooth-scroll: true
---

```{=html}
<style>

mark {
  background-color: #ece985;
  color: black;
  border-radius: 5px; 
  padding: 0.2em;
}

mark-2 {
  background-color: #840a73;
  color: white;
  border-radius: 5px; 
  padding: 0.2em;
}

red {
  color: #9b1212;
}

</style>
```
# Course Description

Capstone Research Seminar offers an opportunity for GLOA MA students to draw upon the different skills and bodies of knowledge acquired and honed during the course MA studies. The goal is to prepare the students to operate professionally in a complex global environment that requires a range of analytical skills. We tap into your previous coursework which has so far trained you to think critically of your own orientations, worldview, and presuppositions. In this class, you will apply them to a specific research project of your choice. While we start out talking extensively about social science research methods, the course is not a research methods course. Nor is it a \`repeat of GLOA 605'. Rather it sets out to explore ways in which we can link theories and concepts to methods in order to generate new knowledge and persuasive arguments. The underlying assumption is that in order to operate effectively in a global age, we need to know not only how to produce knowledge and arguments but also assess and evaluate those made by others, their (implicit or explicit) presuppositions, blind spots, and understandings. The frequent presentations as well as peer-review assignments are to incorporate these assumptions into an effective learning process. As such, this seminar is not to turn you into an academic. Instead, it is a collective learning experience focusing on analytical speaking, writing, and communications. All those efforts will be reflected in your final outcome of the class, a **capstone research paper**.

# Course Schedule and Readings

-   Unless specified as <mark>not required</mark>, all the listed readings are required readings.
    -   Required readings are indispensable for your successful completion of this course.
    -   <mark>not required</mark> readings might still be tremendously helpful and you are strongly encouraged to finish them too.
-   Some readings might have hyperlinks. Others don't. It doesn't matter. You should be able to find almost all readings in the syllabus in <red>PDF</red> in [Fenwick library](https://library.gmu.edu/) because all the reference information is provided. 
-   Readings and the schedules are subject to change.
-   You are expected to complete the reading within the first three days of the week.

<!-- For now it's hard to find an equivalent to \bibentry. In QMD Visual model, when @citekey is recognized, a pop-up shows the full citation. for now I just copy-and-paste that and replace the citekey with it.  -->

## Week 1. Introduction and Social Science Methods Recap

-   King, Gary, Robert O. Keohane, and Sidney Verba. 1994. *Designing Social Inquiry: Scientific Inference in Qualitative Research*. Princeton: Princeton University Press.

-   Vennesson, Pascal. 2008. “Case Studies and Process Tracing: Theories and Practices.” In eds. Donatella della Porta and Michael Keating. *Approaches and Methodologies in the Social Sciences: A Pluralist Perspective*. New York: Cambridge University Press, 223–39. <mark>not required</mark>

-   Pape, Robert A. 2008. “[Methods and Findings inthe Study of Suicide Terrorism](https://doi.org/10.1017/S0003055408080179).” *American Political Science Review* 102(2): 275–77.
